### ISSUE TITLE
How to use NuxtImage inside content

### ISSUE THREAD

**Issue by anjali89r** [debs-obrien/debbie.codes#431]
I was using your template for my blog and am facing issues with the images inside the MD files. 
For example, the image below in this [section](https://github.com/debs-obrien/debbie.codes/blob/master/content/blog/how-to-locate-elements-in-playwright.md#playwrights-test-generator) renders correctly for you since you gave the full Cloudinary URL. I was wondering if there is a way to use NuxtImg here instead of providing the entire URL

**Comment by debs-obrien** [comment]
HiI think you just have to make it a component and use the component inside the markdownDebbieSent from my iPhoneOn 3 Feb 2023, at 16:25, Anjali R ***@***.***> wrote:﻿
I was using your template for my blog and am facing issues with the images inside the MD files.
For example, the image below in this section renders correctly for you since you gave the full Cloudinary URL. I was wondering if there is a way to use NuxtImg here instead of providing the entire URL
